env:
  browser: true
  es6: true
  node: false
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:jest/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
settings:
  react:
    version: 6.12.1
rules: {
  "jest/no-mocks-import": 0,
  "jest/valid-expect": 0
}
