language: node_js
node_js:
  - 13.1.0
cache:
  yarn: true
  directories:
    - ~/.cache
    -~/.npm
before_script:
  - yarn
  - cypress install
  - yarn start --silent &
script:
  - yarn test
  - npx cypress run
